# This is a mix of the basic and tidyverse workflow

name: CI

# Controls when the action will run.
on:

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  R-CMD-check:

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', rtools-version: '42'}
          - {os: ubuntu-latest,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest", http-user-agent: "R/4.3.0 (ubuntu-latest) R (4.3.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      # _R_CHECK_RD_XREFS_: false
      # _R_CHECK_CRAN_INCOMING_: false
      # _R_CHECK_AUTOCONF_: false
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          rtools-version: ${{ matrix.config.rtools-version }}

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::patchDVI

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args:  '"--no-build-vignettes"'
          args:  '"--no-build-vignettes"'

